name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - manifest: west-ncs.yml
            target: nrf9160dk/nrf9160/ns
            app: gateway
            sysbuild: true
          - manifest: west-ncs.yml
            target: nrf9160dk/nrf52840
            app: controller
            sysbuild: false
          - manifest: west-ncs.yml
            target: thingy91x/nrf9151/ns
            app: gateway
            sysbuild: true
          - manifest: west-thingy91x-controller.yml
            target: thingy91x/nrf5340/cpunet
            app: controller
            sysbuild: true
            extra_args: -DSB_CONF_FILE=sysbuild/nrf5340_cpuapp.conf
          - manifest: west-zephyr.yml
            target: frdm_rw612
            app: gateway
            sysbuild: false
            blobs: hal_nxp
    container: golioth/golioth-zephyr-base:0.17.0-SDK-v0
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.17.0
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: bluetooth-gateway

      - name: Init and update west
        run: |
          west init -l bluetooth-gateway --mf ${{ matrix.manifest }}
          west update --narrow -o=--depth=1
          git config --global user.email user@git-scm.com
          git config --global user.name "Git User"
          west patch apply || true

      - name: Manual Patch
        if: ${{ matrix.manifest == 'west-thingy91x-controller.yml' }}
        run: |
          west forall zephyr -c "git am $GITHUB_WORKSPACE/bluetooth-gateway/zephyr/patches/thingy91x-controller/zephyr/*.patch"

      - name: Install pip packages
        run: |
          uv pip install \
            -r zephyr/scripts/requirements-base.txt

          uv pip install            \
            cryptography==41.0.7  \
            pyasn1                \
            pyyaml                \
            cbor>=1.0.0           \
            imgtool>=1.9.0        \
            jinja2                \
            click

      - name: Fetch Binary Blobs
        if: ${{ matrix.blobs }}
        run: west blobs fetch ${{ matrix.blobs }}

      - name: Build
        id: build
        env:
          TARGET: ${{ matrix.target }}
        shell: bash
        run: |
          west build \
            -b $TARGET \
            bluetooth-gateway/${{ matrix.app }} \
            ${{ matrix.sysbuild && '--sysbuild' || '--no-sysbuild' }} \
            -- ${{ matrix.extra_args }}

          echo "ARTIFACT_TARGET=${TARGET//\//-}" >> $GITHUB_OUTPUT

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}-${{ steps.build.outputs.ARTIFACT_TARGET }}
          path: |
            build/${{ matrix.sysbuild && matrix.app || '' }}/zephyr/zephyr.hex
            build/${{ matrix.sysbuild && matrix.app || '' }}/zephyr/zephyr.elf
            build/${{ matrix.sysbuild && matrix.app || '' }}/zephyr/zephyr.map
            ${{ (matrix.sysbuild && (matrix.manifest == 'west-ncs.yml') && 'build/dfu_application.zip') || '' }}
